version: '3.1'

services:
  app:
    build:
      context: ./
      dockerfile: ./dockers/node/Dockerfile
    container_name: app
    restart: unless-stopped    
    ports:
      - "3000:3000"
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    working_dir: /application
    #environment:
      # provide your credentials here
      #- MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      #- MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      #- MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"